[0]
last_run_time = 1762142122
path = 'C:\Users\AlexK\OneDrive\Documents\xeniamanager\xenia-manager\dashboard\2005.11.22 - Blades (2.0.1888.0)(original shipped version)\dash.xex'
title_name = 'Xbox Dashboard'