[0]
last_run_time = 1762187409
path = 'C:\Users\AlexK\OneDrive\Documents\xeniamanager\xenia-manager\games\The Orange Box\Orange Box, The (World) (En,Fr,De).iso'
title_name = 'The Orange Box'

[1]
last_run_time = 1762187337
path = 'C:\Users\AlexK\OneDrive\Documents\xeniamanager\xenia-manager\games\Crysis 2\Crysis 2 (World) (En,Fr).iso'
title_name = 'CrysisÂ®2'

[2]
last_run_time = 1762187128
path = 'C:\Users\AlexK\OneDrive\Documents\xeniamanager\xenia-manager\dashboard\dashboards\2006.11.30 - Blades (2.0.4548.0)\bootanim.xex'
title_name = ''

[3]
last_run_time = 1762187064
path = 'C:\Users\AlexK\OneDrive\Documents\xeniamanager\xenia-manager\dashboard\dashboards\2006.11.30 - Blades (2.0.4548.0)\$flash_dash.xex'
title_name = 'Xbox 360 Dashboard'

[4]
last_run_time = 1762185321
path = 'C:\Users\AlexK\OneDrive\Documents\xeniamanager\xenia-manager\dashboard\dashboards\2006.11.30 - Blades (2.0.4548.0)\dash.xex'
title_name = 'Xbox Dashboard'